### ISSUE TITLE
One stupid question about := and =

### ISSUE THREAD

**Issue by iredmail** [vlang-io/V#14]
From doc:

```
const PI = 3.14   // case 1

mut age := 20
age = 21    // case 2
```

Why we cannot use `:=` for both cases?

I don’t have C/C++ experience, so this may be very stupid question. 
But if it doesn't require programmer to remeber one more thing (i don’t mind the syntax parser and compiler to remeber more for me) that would be even better.

Btw, will we see pattern match support like Erlang?

**Comment by medvednikov** [comment]
`:=` declares a variable

`=` assigns a value

If you use `:=` everywhere then you end up with the same problem Python has: variables are not declared. This results in a huge mess.

**Comment by iredmail** [comment]
Didnt expect a fast reply. Thanks @medvednikov. :)

Any plan to release a binary package of V itself soon? Let people have some fun. :)

**Comment by medvednikov** [comment]
An online playground will be available in a couple of days.

**Comment by iredmail** [comment]
Cool. Will wait for it. :)
