### ISSUE TITLE
Optional type enhancements

### ISSUE THREAD

**Issue by ntrel** [vlang-io/V#15]
Optional types is a great feature. I think there should be a way to declare an empty optional type such as:
```c
mut opt := T?() // syntax like T(v) conversion syntax but without a value v
// with built-in function instead
mut opt := empty<T>()
```
(This should require a mutable variable otherwise it isn't useful). Quite often there is no valid value to initialize a variable with. [Here](https://news.ycombinator.com/item?id=19104598) dkersten argues against using a valid value temporarily instead of an empty option type, when the value should be set later on, perhaps with complex logic.

Also, the docs show the `or` statement, which requires an error block to exit the current scope. There could also be an `and` statement:
```c
v := opt and {
  // v is in scope here only
} else {
  // handle err and continue below
}
// only opt is in scope here
```
This works for one optional value, but sometimes there are more than one - perhaps pattern matching is needed to handle cases where e.g. the programmer needs a value from either `opt1` *xor* `opt2`.

**Comment by medvednikov** [comment]
Can you give an example of where you'd need it?
Thanks

**Comment by ntrel** [comment]
```c
mut opt := T?()
mut opt T? := empty // alternately, have a magic `empty` literal, does same thing
if complex_logic {
  ...
  opt = create_T()
}
else if other_complex_logic {
  ...
  opt = other_create_T()
}
// here opt may have been assigned a value, or maybe not
// we don't want to repeat all the complex logic, we just test if opt has a value
v := opt and {
  v.doSomething()
  ...
}
...
```
Also, structs might have an optional type field, and initializing the struct should allow keeping the optional field empty:
```c
struct S {
  name string
  child Child?
}
// no initializer for child, leave empty 
// sue doesn't have a child yet
s := S('sue')
// or maybe useful to have empty literals in case there are more fields added to S
s := S('sue', Child?(), some_other_field_initializer)
// or a magic `empty` literal instead of T?()
// which is also useful for resetting an optional field/variable
s.child = empty;
assert !s.child
```
An empty optional variable doesn't indicate an error necessarily, just that the value doesn't exist yet.

**Comment by medvednikov** [comment]
Ah, I see. There will be `None`.

**Comment by medvednikov** [comment]
Does `None` solve this @ntrel ?

**Comment by ntrel** [comment]
@medvednikov Sorry for the late reply. TODO:

- [ ] Decide syntax for declaring empty optional variables - maybe `mut opt := T?(None)`
- [ ] Allow struct optional fields without initializers:
```c
struct S {i int; opt T?}
s := S{5} // no initializer required for opt
```
- [ ] Add `and` statement:
```c
v := opt and {
  // do something with v
}
// do something else, whether opt had a value or not
```
If you like I'm happy to update the docs for this.

**Comment by ntrel** [comment]
@medvednikov Does this sound OK? If you prefer I can make a new issue for this. Also once the code is available I could maybe look at implementing the last two items.
