### ISSUE TITLE
About runtime.wait

### ISSUE THREAD

**Issue by conilas** [vlang-io/V#18]
Hey!

Was just reading the docs of the lang. Nice project!

But I do have some points. 

For example, using ```runtime.wait``` (as shown in https://vlang.io/compare) to wait for all coroutines to end... How did one gets to that?

Let's say I use it inside a nested coroutine - what would happen? Would it wait for the nested coroutine or for all the coroutines? 

Is the runtime keeping the scope of the coroutines where the wait method is called? 

The CSP idea that Go uses seems better in this case - I'd have to send a message through the channel and could go on with my life. I do not want to wait for this - why can't I have it is an Async way?

Also, here goes (maybe) a problem: If I create a coroutine that only calls runtime.await(). Does it wait itself (as a coroutine) to end the call? Because it looks like it'd get stuck - if I'm waiting for the coroutines to end and I'm a coroutine, I'll never end.

Well, was just wondering about this. Would love to discuss more about the language itself - if possible! 

Again, nice project! Hope to see some updates :-)

**Comment by medvednikov** [comment]
Hey

runtime.wait is a temporary hack, it can only be called from the main thread. I haven't fully figured out concurrency yet. It will be similar to Go.

**Comment by elimisteve** [comment]
Please add Go-style `chan`s to V! Would make a fantastic addition.
