### ISSUE TITLE
Underscore separators?

### ISSUE THREAD

**Issue by malexdev** [vlang-io/V#19]
This looks quite cool! Looking forward to seeing more and hopefully helping out at some point.

What is the reason for "going against the grain" and using `_` separators instead of `camelCase` for identifiers?

In #3, you mention that the reason you prefer `'` and \` for characters over `"` is that you don't want to have to press <kbd>shift</kbd>. That argument resonates with me.

In keeping with that theme, isn't it more efficient and easier to use camel case over underscores? The camel case method doesn't require you to reach a satellite key, plus is more normal for users in most languages (in my experience at least).

I guess it just seems odd to make so much of the language feel very similar to Go, but then abandon camel casing.

Just a thought. Do with it what you will :smile:

**Comment by medvednikov** [comment]
I swapped - and _ :)

I wouldn't say it's going against the grain. C/C++, Python, Rust, Ruby, Perl etc use underscores.

**Comment by malexdev** [comment]
That’s fair. I think my main thought was:

If we are micro optimizing to the extent that ‘ is preferred over “, then surely camel case is more efficient than snake case. 

That was all. And of course not trying to like, argue the point really. It just stuck out to me. 

Either way looks great! Can’t wait!
