### ISSUE TITLE
Can you release the closed-source compiler right now for us to play?

### ISSUE THREAD

**Issue by SRGOM** [vlang-io/V#2]
I am not crazy about open-source unlike others so would be okay with trying your compiler- I want to see the GUI story.

**Comment by medvednikov** [comment]
Hi,

I'd love to release it as quickly as possible, but what you are asking can't be done right now. It will take too much time, and I have a huge backlog.

In late February vlang.io will have an online playground (like play.golang.org), so at least you'll have access to the compiler there (no GUI though).
