### ISSUE TITLE
Skipping imports

### ISSUE THREAD

**Issue by medvednikov** [vlang-io/V#20]
I just found out that in Rust 2018 fully qualified paths don’t require `use` or `extern crate`.  What do you think about not requiring `import http` in
```
fn main() { 
  http.get('http://example.com')? 
}
```

I guess seeing all dependencies in one place is nice. And the language will automatically insert them anyway.

**Comment by robertbakker** [comment]
What happens if there's two packages with same name ? 

Or will it be more along the lines of

```
fn main() { 
  vendor1.http.get('http://example.com')? // does not require import
  vendor2.http.get('http://example.com')? // does not require import
}
```

What about aliasing like in Go ?

**Comment by medvednikov** [comment]
The import syntax for more complex modules is going to be 'import a.b.foo'

If there are name conflicts, there will be a way to define aliases. Not sure about the syntax yet. Something like `import myfoo a.b.foo`.

**Comment by jkaye2012** [comment]
Perhaps the Python-esque `import a.b.foo as myfoo`?

**Comment by medvednikov** [comment]
Maybe. Although this requires a new keyword.

**Comment by medvednikov** [comment]
After giving it a thought I decided it goes against one of the main philosophies of V: only one way of doing things. If this is implemented, some modules will be skipped, others will be imported. This results in inconsistencies. 

V will automatically insert all missing imports anyway. And for large projects it's always good to see all imports in the file's header.

**Comment by 1l0** [comment]
Can I write something like
```go
import( 
    http
    json
    runtime
)
```
as in Go?
