### ISSUE TITLE
Future feature to end `or` blocks with a print function?

### ISSUE THREAD

**Issue by naltun** [vlang-io/V#26]
https://github.com/vlang-io/V/blob/224e6dba066da3da6f620ff6dd42edf1bac27844/examples/users.v#L32

In `users.v`, there is a call to `eprintln` before the return. Are there plans to alter the compiler to allow this print call to be the end of the block?

**Comment by naltun** [comment]
Thinking about this, it actually isn't a bad idea. How does `continue` behave differently from `return`ing nothing?

**Comment by medvednikov** [comment]
Sorry, why would `eprintln` be the end of the `or` block?

It just prints to stderr, it's not like Go's `log.Fatal`

**Comment by naltun** [comment]
> Sorry, why would eprintln be the end of the or block?

Because adding a `return` with no values seems verbose. It is not unusual practice, though. The `or` block is for handling errors, right? So if the compiler sees the block ending with `eprintln` then it could understand the end of the block, and return as normal.

I'm not sure if this is 1) even desired, or 2) an easy patch to make. Empty `return`s have always struck me as odd.

**Comment by naltun** [comment]
The `continue` keyword doesn't seem like a bad idea. Closing.
