### ISSUE TITLE
Website comparison out of date with repo

### ISSUE THREAD

**Issue by brandonros** [vlang-io/V#34]
![image](https://user-images.githubusercontent.com/8949910/54580173-52f68b00-49dd-11e9-8675-1140afe82da5.png)

https://github.com/vlang-io/V/blob/master/website/templates/compare.html#L150

**Comment by medvednikov** [comment]
Indeed, I have two different repos, I need to merge them into one. Will do asap.

**Comment by ntrel** [comment]
@medvednikov It would be good when you get time to put the website on github so we can monitor changes to the docs etc.

**Comment by ntrel** [comment]
Looks like the website repo is [here](https://github.com/vlang-io/website) :-)
