### ISSUE TITLE
Official web site don't open in my browser

### ISSUE THREAD

**Issue by angelopolotto** [vlang-io/V#37]
I want to read more about the project but I can't open the official web site since yesterday. I don't know if It it a issue but this can be a channel to warn the community about that.

Thank you in advance.

**Comment by medvednikov** [comment]
Hi 

This is really strange

Can you send me a screenshot to support@volt-app.com <mailto:support@volt-app.com>?

Thanks

**Comment by medvednikov** [comment]
Just checked with various tools that open the site globally: works fine.

**Comment by angelopolotto** [comment]
I tried again and It worked well. I don't know what was happening. 
Thank you for your attention!

**Comment by medvednikov** [comment]
Cool. Maybe something with your network/firewall/AV etc
