### ISSUE TITLE
Android and IOS

### ISSUE THREAD

**Issue by hamad-almamari** [vlang-io/V#39]
Is there any plans for Android and Ios support.?
Also can V used to get powerfull graphics over GPUs on deff backends like Metal and OpenGl

**Comment by medvednikov** [comment]
> Is there any plans for Android and Ios support.?

Yes! Hopefully this year.

> Also can V used to get powerfull graphics over GPUs on deff backends like Metal and OpenGl

Yes, it already has a small graphics library `gg`. It uses OpenGL, but it'll be trivial to add other backends.

For example vid uses `gg` for rendering:

https://github.com/medvednikov/vid
