### ISSUE TITLE
IO?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [vlang-io/V#45]
Hi,

Is there (going to be) an IO library included with V?

Thanks!

**Comment by medvednikov** [comment]
Hi 

If you mean file IO, then of course.

**Comment by medvednikov** [comment]
I'll publish package documentation soon.

**Comment by ThatNerdyPikachu** [comment]
What about “memory IO”, like the ability to put data from a HTTP response, or a byte array, into a “stream” in memory of sorts, a la C#?

**Comment by medvednikov** [comment]
Can you give an example?

**Comment by ThatNerdyPikachu** [comment]
```cs
using (Stream stream = new MemoryStream()) {
using (StreamWriter streamW = new StreamWriter(stream)
streamW.WriteUInt64(1111);
}
```

**Comment by medvednikov** [comment]
Yes, it'll be similar to

https://golang.org/pkg/io/

**Comment by ThatNerdyPikachu** [comment]
@medvednikov do you have basic file I/O implemented? because of vid, I’m assuming you do?

**Comment by medvednikov** [comment]
Yes

**Comment by ThatNerdyPikachu** [comment]
To what extent? Reading and writing, maybe metadata, etc?

(if this info will be out with the docs — I’ll stop bugging you :) )

**Comment by medvednikov** [comment]
It will be out with package docs
