### ISSUE TITLE
Pattern match support?

### ISSUE THREAD

**Issue by iredmail** [vlang-io/V#46]
Will V support pattern match like Erlang?

```
Eshell V10.2.3  (abort with ^G)
1> L = [1, 2, 3].
[1,2,3]

2> [X, _, _] = L.
[1,2,3]

3> X.
1
```

**Comment by medvednikov** [comment]
Most likely there will be `match` replacing the current switch, similar to Rust:

https://doc.rust-lang.org/1.15.1/book/match.html

**Comment by iredmail** [comment]
- From `switch` to `match`, that's easier to understand the code.
- But how about pattern match in other statements (like Erlang)?

```
fn main() {
        ...
	[var1, var2, _] := [1, 2, 3]
        ...
}
```

**Comment by medvednikov** [comment]
I'm not familiar with Erlang, if this does what I think it does, you'll be able to achieve this with

var1, var2 := 1, 2

Like in Go

**Comment by iredmail** [comment]
Thanks. This is not mentioned in document (yet). :)

**Comment by medvednikov** [comment]
Yeah it will be once it’s implemented.
