### ISSUE TITLE
Does vlang have a golang type keyword?

### ISSUE THREAD

**Issue by zeromake** [vlang-io/V#48]
vlang declare `interface`, `struct` different from golang not use `type`.
vlang
``` text
interface Speaker {
    speak() string
}
struct Point {
    x int
    y int 
} 
```
golang
``` go
type Speaker interface {
    speak() string
}
type Point struct {
    x int
    y int 
} 
```
golang `type` keyword Can also be used as type alias.
E.g `context.Context` and `golang.org/x/net/context.Context` type alias

**Comment by medvednikov** [comment]
It does. For example:

`type MyFn fn (a, b int)`

This will be documented soon.

Originally I used Go's syntax `type Foo struct` but then decided to go with traditional C syntax for brevity.
