### ISSUE TITLE
A V program must have a main function

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang-io/V#53]
The following program:

fn main2() { 
        types := ['game', 'web', 'tools', 'GUI']
        for typ in types {
                println('Hello, $typ developers!')
        }
} 

gives You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
It should give a better message like: undefined: main() function

**Comment by medvednikov** [comment]
Fixed: `function main is undeclared in the main module`

**Comment by Ivo-Balbaert** [comment]
Thanks!
