### ISSUE TITLE
Cannot compile and run program that print pointer value

### ISSUE THREAD

**Issue by shouji-kazuo** [vlang-io/V#56]
I played Vlang playground(https://vlang.io/play), then found a bug.
This is just a short note to inform you.
----
Steps to reproduce:
1. Enter program list as below
```
fn main() {
	u := 100
	println(&u)
}
```
2. Click Run button
3. The outut was below.
`You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`
----
(My English was maybe something wrong, sorry.)

**Comment by shouji-kazuo** [comment]
```
fn main() {
	u := "100"
	println(&u)
}
```

↓
`test.v:2
unexpected token `INT``

**Comment by medvednikov** [comment]
こんにちは

```
fn main() {
	u := 100
	println(&u)
}
```

This has been fixed, thanks for reporting.


```
fn main() {
	u := "100"
	println(&u)
}
```

V uses `'` for strings, I'll make it complain about using `"`.

**Comment by naltun** [comment]
@medvednikov In V, what is the use case for using `"` (double quotes)?

**Comment by medvednikov** [comment]
Right now `"` is not supported at all.

**Comment by medvednikov** [comment]
> V uses ' for strings, I'll make it complain about using ".

Done.

**Comment by naltun** [comment]
> Right now " is not supported at all. And I'm not sure I want to add double quotes, since having only one way to denote strings makes the language more consistent and simpler.

I absolutely love this idea. It's something that I love about Go. Nice. 👍

**Comment by zac-garby** [comment]
I think it’s worth having ‘ and “ for strings, because if you want to write a string with a ‘ character inside it you can use “ strings instead of using an escape character, which is arguably nicer.

**Comment by naltun** [comment]
> I think it’s worth having ‘ and “ for strings, because if you want to write a string with a ‘ character inside it you can use “ strings instead of using an escape character, which is arguably nicer.

So wouldn't the easiest thing to do be to make double quotes the _only_ way to make strings? That way, single quotes can be easily added. If double quotes want to be added, strings can have two single quotes. Or maybe escaped double quotes.

**Comment by medvednikov** [comment]
From my own experience, double quotes are used a lot more often in strings (for example JSON).

**Comment by zac-garby** [comment]
I agree in a way, but it depends entirely on what you’re doing. For example, if you’re writing a sentence and use the word “they’re”, it will be advantageous to not have to escape that.

To be honest though, if I had to choose one, it would be double-quotes, because I tend to associate single-quotes with single characters.

**Comment by naltun** [comment]
@medvednikov Any way to switch V from having single quotes to using double quotes for enclosing strings?

**Comment by shouji-kazuo** [comment]
@medvednikov 
Thanks a lot!
ありがとうございました!
