### ISSUE TITLE
Can't pass array as function argument

### ISSUE THREAD

**Issue by pocket7878** [vlang-io/V#57]
Hi!
I played playground, then found a bug.

Steps to reproduce:
Enter a program:
```
fn reverse(dummy []int) {
}

fn main() {
        arr := [1]
	println(reverse(arr))
}
```
2. Run
3. Then I got an error message:
```
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
```

**Comment by medvednikov** [comment]
Hi

Functions need to return values, there's no error message for that right now, I'll fix it today.

**Comment by medvednikov** [comment]
`fn reverse(dummy []int) []int {`

**Comment by medvednikov** [comment]
Fixed.
