### ISSUE TITLE
Cannot compile program that contains method that has pointer type receiver

### ISSUE THREAD

**Issue by shouji-kazuo** [vlang-io/V#58]
Steps to reproduce:

1. Enter program list as below:
```
struct Foobar {
  member int
}

fn (f *Foobar) do() { // method of pointer type receiver
  println('I am foobar')
}

fn main() {
  f := Foobar{}
  f.do() // I think f is type of "Foobar", but I assume that f can treat as pointer type with implicit conversion ( like Golang )
} 
```
2. Click Run button
3. The output was shown as below.
`You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

**Comment by medvednikov** [comment]
The correct syntax is 

```
struct Foobar {
	member int
}

fn (f mut Foobar) do() {
	// method of pointer type receiver
	println('I am foobar')
}

fn main() {
	f := Foobar{}
	f.do()// I assume f is type of "Foobar", but can treat as pointer type with implicit conversion ( like Golang )
}

```

**Comment by medvednikov** [comment]
`(f mut Foobar)` instead of `(f *Foobar)`

I'll update the compiler so that `(f *Foobar)` doesn't compile.

**Comment by medvednikov** [comment]
>  I assume f is type of "Foobar", but can treat as pointer type with implicit conversion ( like Golang )


This assumption is correct :)

**Comment by shouji-kazuo** [comment]
OK, I understood.
ありがとうございました m(_ _)m

**Comment by medvednikov** [comment]
Fixed.

You should now get `use (f mut Foobar) instead of (f *Foobar) `

**Comment by shouji-kazuo** [comment]
I have confirmed .
thanks a lot!

**Comment by ntrel** [comment]
>  f is type of "Foobar", but can treat as pointer type with implicit conversion

I don't think letting pointers implicitly dereference is a good idea, and it seems to go against the simple philosophy of V:
```rust
mut i := 5
p := &i
i = p // confusing, should be an error
i = *p // OK
```
