### ISSUE TITLE
Compilation speed benchmark bias?

### ISSUE THREAD

**Issue by lnmds** [vlang-io/V#8]
(using https://github.com/vlang-io/V/blob/ffd6c1511ccbcd624b96cf730778b03309cf5eee/website/compilation_speed_test_gen.v as a reference)

All other languages include some kind of I/O or a `puts` / print calls on their benchmark codes, except V's benchmark code. Is there a reason for this?

**Comment by medvednikov** [comment]
Good catch. Fixed.

Would be a ridiculous bias :) 

I add files manually via GitHub editor here because I haven't set up the dual repository thing.

That's my changes don't often get synced. Originally I was printing only once.

The compilation time is 0.6s with the printing.
